name:  daily
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest 
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        User: ${{ github.event.repository.owner.id }}
    steps:

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
          npm install cron
          npm install request
          npm install md5-node
          node Task/dsjtx1.js
      - name: 'run 【ttdt】'
        run: |
          node Task/ttdt.js
